Exit with success if item is missing

diff --git a/terraform-credentials-keychain b/terraform-credentials-keychain
--- a/terraform-credentials-keychain
+++ b/terraform-credentials-keychain
@@ -15,7 +15,17 @@ fi
 
 case "$1" in
   get)
-    token=$(security -q find-generic-password -s "$SERVICE" -a "$2" -w)
+    ret=0
+    token=$(security -q find-generic-password -s "$SERVICE" -a "$2" -w 2>&1) || ret=$?
+    # Item not found: exit 0 with empty credentials response
+    if [ "$ret" == 44 ]; then
+      echo "{}"
+      exit 0
+    # Other errors should result in failure
+    elif [ "$ret" != 0 ]; then
+      echo $token
+      exit $ret
+    fi
     cat <<EOF
 {
     "token": "${token}"
